# Generated by Django 3.1.5 on 2021-01-22 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, max_length=100)),
                ('photo_name', models.CharField(blank=True, max_length=50)),
                ('photo_img', models.ImageField(upload_to='images/%Y/%m/%d/')),
                ('on_grid', models.BooleanField(default=False)),
                ('photo_album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='albums.album')),
            ],
        ),
    ]
