# Generated by Django 3.1.5 on 2021-01-20 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_name', models.CharField(max_length=50)),
                ('photo_description', models.CharField(max_length=500)),
                ('photo_img', models.ImageField(upload_to='images/% Y/% m/ % d/')),
            ],
        ),
        migrations.DeleteModel(
            name='Pictur',
        ),
    ]
