# Generated by Django 3.1.5 on 2021-01-20 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210120_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='on_grid',
            field=models.BooleanField(default=False),
        ),
    ]
