# Generated by Django 3.1.5 on 2021-02-11 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_picture_photo_alt_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='album_cover',
            field=models.BooleanField(default=False),
        ),
    ]
