# Generated by Django 3.1.5 on 2021-01-20 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_picture_on_grid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='photo_img',
            field=models.ImageField(upload_to='images/%Y/%m/%d/'),
        ),
    ]
