# Generated by Django 3.1.5 on 2021-02-11 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_events'),
        ('home', '0003_picture_album_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='event_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='albums.events'),
        ),
    ]
