# Generated by Django 3.1.5 on 2021-01-21 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photographer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('bio', models.CharField(max_length=1000)),
                ('photo', models.ImageField(upload_to='images/%Y/%m/%d/')),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
