# Generated by Django 3.1.5 on 2021-01-25 23:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100)),
                ('l_name', models.CharField(max_length=200)),
                ('email_address', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(max_length=10)),
                ('client_notes', models.TextField(blank=True)),
                ('request_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
